name: Ubuntu - Test

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '15 */6 * * *'

jobs:
  build:
    name: Test on Ubuntu
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      #- name: Set up Zalenium
      #  run: docker-compose -f docker-compose.yml up --force-recreate -d
      - name: Set up Native Selenium Grid
        run: docker-compose -f docker-compose_native.yml up --scale chrome=4 --remove-orphans -d
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Check running containers
        run: docker ps

      - name: Run all tests
        continue-on-error: true
        run: mvn test -DexecutionAddress="localhost:4444" -DtargetOperatingSystem="Linux-64" -DmaximumPerformanceMode="2" -DtargetBrowserName="GoogleChrome" -Dtest="!%regex[.*cucumber.*], !%regex[.*Runner.*]"

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report with history
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          subfolder: allure

      - name: Deploy Allure report to Github Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history/allure
          destination_dir: allure
          publish_branch: gh-pages

      - name: Post the link to the Allure report
        if: always()
        continue-on-error: true
        uses: Sibz/github-status-action@v1.1.6
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Allure Test Execution Report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: https://ismail-elshafeiy.github.io/TestAutomation/allure/${{ github.run_number }}
